name: Template Test

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  publish:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: echo "${{ inputs.name }}"
